######################################################################
# Automatically generated by qmake (3.1) Sun Jun 21 16:00:59 2026
######################################################################

TEMPLATE = app
TARGET = SurfaceExplorer
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_UP_TO=0x060000 # disables all APIs deprecated in Qt 6.0.0 and earlier

# Input
HEADERS += audiocontroller.h \
           expressionparser.h \
           exprtk.hpp \
           geodesiccalculator.h \
           geometrybuilder.h \
           glsltranslator.h \
           glwidget.h \
           inputhandler.h \
           inputvalidator.h \
           librarydragdrophandler.h \
           libraryfileoperations.h \
           librarymanager.h \
           librarymenucontroller.h \
           mainwindow.h \
           nativevideoencoder.h \
           presetserializer.h \
           surfaceengine.h \
           synthesizer.h \
           uistylemanager.h \
           videorecorder.h \
           build/SurfaceExplorer_autogen/include/ui_mainwindow.h \
           build/Desktop_Qt_6_10-Debug/SurfaceExplorer_autogen/include/ui_mainwindow.h \
           build/Qt_6_10_1_for_Android_arm64_v8a-Debug/SurfaceExplorer_autogen/include/ui_mainwindow.h \
           build/Qt_6_10_1_ios_d1aea6/SurfaceExplorer_autogen/include_Debug/ui_mainwindow.h \
           build/Qt_6_10_1_ios_d1aea6/SurfaceExplorer_autogen/include_MinSizeRel/ui_mainwindow.h \
           build/Qt_6_10_1_ios_d1aea6/SurfaceExplorer_autogen/include_Release/ui_mainwindow.h \
           build/Qt_6_10_1_ios_d1aea6/SurfaceExplorer_autogen/include_RelWithDebInfo/ui_mainwindow.h \
           build/Qt_6_10_1_ios_d1aea6/build/SurfaceExplorer.build/Debug-iphoneos/DerivedSources/GeneratedAssetSymbols.h
FORMS += mainwindow.ui
SOURCES += audiocontroller.cpp \
           geodesiccalculator.cpp \
           geometrybuilder.cpp \
           glsltranslator.cpp \
           glwidget.cpp \
           inputhandler.cpp \
           inputvalidator.cpp \
           librarydragdrophandler.cpp \
           libraryfileoperations.cpp \
           librarymanager.cpp \
           librarymenucontroller.cpp \
           main.cpp \
           mainwindow.cpp \
           presetserializer.cpp \
           surfaceengine.cpp \
           synthesizer.cpp \
           uistylemanager.cpp \
           videorecorder.cpp \
           build/SurfaceExplorer_autogen/mocs_compilation.cpp \
           build/Desktop_Qt_6_10-Debug/SurfaceExplorer_autogen/mocs_compilation.cpp \
           build/Qt_6_10_1_for_Android_arm64_v8a-Debug/SurfaceExplorer_autogen/mocs_compilation.cpp \
           build/Qt_6_10_1_ios_d1aea6/SurfaceExplorer_autogen/mocs_compilation.cpp \
           build/SurfaceExplorer_autogen/EWIEGA46WW/qrc_resources.cpp \
           build/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           build/Desktop_Qt_6_10-Debug/SurfaceExplorer_autogen/EWIEGA46WW/qrc_resources.cpp \
           build/Qt_6_10_1_for_Android_arm64_v8a-Debug/SurfaceExplorer_autogen/EWIEGA46WW/qrc_resources.cpp \
           build/Qt_6_10_1_ios_d1aea6/SurfaceExplorer_autogen/EWIEGA46WW/qrc_resources.cpp \
           build/Desktop_Qt_6_10-Debug/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           build/Qt_6_10_1_for_Android_arm64_v8a-Debug/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           build/Qt_6_10_1_ios_d1aea6/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           build/Qt_6_10_1_ios_d1aea6/SurfaceExplorer_autogen/include_Debug/EWIEGA46WW/qrc_resources_CMAKE_.cpp \
           build/Qt_6_10_1_ios_d1aea6/SurfaceExplorer_autogen/include_MinSizeRel/EWIEGA46WW/qrc_resources_CMAKE_.cpp \
           build/Qt_6_10_1_ios_d1aea6/SurfaceExplorer_autogen/include_Release/EWIEGA46WW/qrc_resources_CMAKE_.cpp \
           build/Qt_6_10_1_ios_d1aea6/SurfaceExplorer_autogen/include_RelWithDebInfo/EWIEGA46WW/qrc_resources_CMAKE_.cpp
RESOURCES += resources.qrc
TRANSLATIONS += build/Desktop_Qt_6_10-Debug/CMakeFiles/SurfaceExplorer.dir/compiler_depend.ts \
                build/Desktop_Qt_6_10-Debug/CMakeFiles/SurfaceExplorer_autogen.dir/compiler_depend.ts \
                build/Desktop_Qt_6_10-Debug/CMakeFiles/SurfaceExplorer_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/Qt_6_10_1_for_Android_arm64_v8a-Debug/CMakeFiles/_qt_internal_apk_dependencies.dir/compiler_depend.ts \
                build/Qt_6_10_1_for_Android_arm64_v8a-Debug/CMakeFiles/aab.dir/compiler_depend.ts \
                build/Qt_6_10_1_for_Android_arm64_v8a-Debug/CMakeFiles/aar.dir/compiler_depend.ts \
                build/Qt_6_10_1_for_Android_arm64_v8a-Debug/CMakeFiles/apk.dir/compiler_depend.ts \
                build/Qt_6_10_1_for_Android_arm64_v8a-Debug/CMakeFiles/apk_all.dir/compiler_depend.ts \
                build/Qt_6_10_1_for_Android_arm64_v8a-Debug/CMakeFiles/qt_internal_plugins.dir/compiler_depend.ts \
                build/Qt_6_10_1_for_Android_arm64_v8a-Debug/CMakeFiles/SurfaceExplorer.dir/compiler_depend.ts \
                build/Qt_6_10_1_for_Android_arm64_v8a-Debug/CMakeFiles/SurfaceExplorer_autogen.dir/compiler_depend.ts \
                build/Qt_6_10_1_for_Android_arm64_v8a-Debug/CMakeFiles/SurfaceExplorer_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/Qt_6_10_1_for_Android_arm64_v8a-Debug/CMakeFiles/SurfaceExplorer_copy_apk_dependencies.dir/compiler_depend.ts \
                build/Qt_6_10_1_for_Android_arm64_v8a-Debug/CMakeFiles/SurfaceExplorer_make_aab.dir/compiler_depend.ts \
                build/Qt_6_10_1_for_Android_arm64_v8a-Debug/CMakeFiles/SurfaceExplorer_make_aar.dir/compiler_depend.ts \
                build/Qt_6_10_1_for_Android_arm64_v8a-Debug/CMakeFiles/SurfaceExplorer_make_apk.dir/compiler_depend.ts \
                build/Qt_6_10_1_for_Android_arm64_v8a-Debug/CMakeFiles/SurfaceExplorer_other_files.dir/compiler_depend.ts \
                build/Qt_6_10_1_for_Android_arm64_v8a-Debug/CMakeFiles/SurfaceExplorer_prepare_apk_dir.dir/compiler_depend.ts
